package com.example.thecars.lists

import com.example.thecars.R
import com.example.thecars.classes.Brand


val allBrandsList = listOf(
Brand(name = "Acura", logo = R.drawable.unknown, modelList = acuraModels),
Brand(name = "BMW", logo = R.drawable.bmw, modelList = bmwModels),
Brand(name = "Alfa Romeo", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Aston Martin", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Audi", logo = R.drawable.audi, modelList = emptyList()),
Brand(name = "Aurus", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Bentley", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Buick", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Cadillac", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Changan", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Chery", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Chevrolet", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Chrysler", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Citroen", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Daewoo", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Daihatsu", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Datsun", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Dodge", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "EXEED", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "FAW", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Ferrari", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Fiat", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Ford", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "GAC", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "GMC", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Geely", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Genesis", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Great Wall", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Haval", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Honda", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Hongqi", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Hummer", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Hyundai", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Infiniti", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Isuzu", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "JAC", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Jaguar", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Jeep", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Jetour", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Jetta", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Kaiyi", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Kia", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "LADA", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Lamborghini", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Land Rover", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Lexus", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Lifan", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Lincoln", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Livan", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Lotus", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Mini", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Maserati", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Maybach", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Mazda", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "McLaren", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Mercedes-benz", logo = R.drawable.mb, modelList = emptyList()),
Brand(name = "Mitsubishi", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Nissan", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "OMODA", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Opel", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Peugeot", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Plymouth", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Polestar", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Pontiac", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Porsche", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "RAM", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Ravon", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Renault", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Rolls-Royce", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Rover", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "SEAT", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Saab", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Scion", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Skoda", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Skywell", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Smart", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "SsangYong", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Subaru", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Suzuki", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Tank", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Tesla", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Toyota", logo = R.drawable.toyota, modelList = emptyList()),
Brand(name = "Volkswagen", logo = R.drawable.volkswagen, modelList = emptyList()),
Brand(name = "Volvo", logo = R.drawable.volvo, modelList = emptyList()),
Brand(name = "Vortex", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Voyah", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "ZEEKR", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "ГАЗ", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "ЗАЗ", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "ЗИЛ", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "ИЖ", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "Москвич", logo = R.drawable.unknown, modelList = emptyList()),
Brand(name = "УАЗ", logo = R.drawable.unknown, modelList = emptyList())
)