package com.example.thecars.lists

import com.example.thecars.R

val carsMap = mapOf(
"Acura" to R.drawable.unknown,
"Alfa Romeo" to R.drawable.unknown,
"Aston Martin" to R.drawable.unknown,
"Audi" to R.drawable.audi,
"Aurus" to R.drawable.unknown,
"BMW" to R.drawable.bmw,
"Bentley" to R.drawable.unknown,
"Buick" to R.drawable.unknown,
"Cadillac" to R.drawable.unknown,
"Changan" to R.drawable.unknown,
"Chery" to R.drawable.unknown,
"Chevrolet" to R.drawable.unknown,
"Chrysler" to R.drawable.unknown,
"Citroen" to R.drawable.unknown,
"Daewoo" to R.drawable.unknown,
"Daihatsu" to R.drawable.unknown,
"Datsun" to R.drawable.unknown,
"Dodge" to R.drawable.unknown,
"EXEED" to R.drawable.unknown,
"FAW" to R.drawable.unknown,
"Ferrari" to R.drawable.unknown,
"Fiat" to R.drawable.unknown,
"Ford" to R.drawable.unknown,
"GAC" to R.drawable.unknown,
"GMC" to R.drawable.unknown,
"Geely" to R.drawable.unknown,
"Genesis" to R.drawable.unknown,
"Great Wall" to R.drawable.unknown,
"Haval" to R.drawable.unknown,
"Honda" to R.drawable.unknown,
"Hongqi" to R.drawable.unknown,
"Hummer" to R.drawable.unknown,
"Hyundai" to R.drawable.unknown,
"Infiniti" to R.drawable.unknown,
"Isuzu" to R.drawable.unknown,
"JAC" to R.drawable.unknown,
"Jaguar" to R.drawable.unknown,
"Jeep" to R.drawable.unknown,
"Jetour" to R.drawable.unknown,
"Jetta" to R.drawable.unknown,
"Kaiyi" to R.drawable.unknown,
"Kia" to R.drawable.unknown,
"LADA" to R.drawable.unknown,
"Lamborghini" to R.drawable.unknown,
"Land Rover" to R.drawable.unknown,
"Lexus" to R.drawable.unknown,
"Lifan" to R.drawable.unknown,
"Lincoln" to R.drawable.unknown,
"Livan" to R.drawable.unknown,
"Lotus" to R.drawable.unknown,
"Mini" to R.drawable.unknown,
"Maserati" to R.drawable.unknown,
"Maybach" to R.drawable.unknown,
"Mazda" to R.drawable.unknown,
"McLaren" to R.drawable.unknown,
"Mercedes-benz" to R.drawable.mb,
"Mitsubishi" to R.drawable.unknown,
"Nissan" to R.drawable.unknown,
"OMODA" to R.drawable.unknown,
"Opel" to R.drawable.unknown,
"Peugeot" to R.drawable.unknown,
"Plymouth" to R.drawable.unknown,
"Polestar" to R.drawable.unknown,
"Pontiac" to R.drawable.unknown,
"Porsche" to R.drawable.unknown,
"RAM" to R.drawable.unknown,
"Ravon" to R.drawable.unknown,
"Renault" to R.drawable.unknown,
"Rolls-Royce" to R.drawable.unknown,
"Rover" to R.drawable.unknown,
"SEAT" to R.drawable.unknown,
"Saab" to R.drawable.unknown,
"Scion" to R.drawable.unknown,
"Skoda" to R.drawable.unknown,
"Skywell" to R.drawable.unknown,
"Smart" to R.drawable.unknown,
"SsangYong" to R.drawable.unknown,
"Subaru" to R.drawable.unknown,
"Suzuki" to R.drawable.unknown,
"Tank" to R.drawable.unknown,
"Tesla" to R.drawable.unknown,
"Toyota" to R.drawable.toyota,
"Volkswagen" to R.drawable.volkswagen,
"Volvo" to R.drawable.volvo,
"Vortex" to R.drawable.unknown,
"Voyah" to R.drawable.unknown,
"ZEEKR" to R.drawable.unknown,
"ГАЗ" to R.drawable.unknown,
"ЗАЗ" to R.drawable.unknown,
"ЗИЛ" to R.drawable.unknown,
"ИЖ" to R.drawable.unknown,
"Москвич" to R.drawable.unknown,
"УАЗ" to R.drawable.unknown)