package com.example.thecars.lists

import com.example.thecars.R
import com.example.thecars.classes.Car

val allCarsList = listOf(
Car(title = "Acura", imageId = R.drawable.unknown),
Car(title = "Alfa Romeo", imageId = R.drawable.unknown),
Car(title = "Aston Martin", imageId = R.drawable.unknown),
Car(title = "Audi", imageId = R.drawable.audi),
Car(title = "Aurus", imageId = R.drawable.unknown),
Car(title = "BMW", imageId = R.drawable.bmw),
Car(title = "Bentley", imageId = R.drawable.unknown),
Car(title = "Buick", imageId = R.drawable.unknown),
Car(title = "Cadillac", imageId = R.drawable.unknown),
Car(title = "Changan", imageId = R.drawable.unknown),
Car(title = "Chery", imageId = R.drawable.unknown),
Car(title = "Chevrolet", imageId = R.drawable.unknown),
Car(title = "Chrysler", imageId = R.drawable.unknown),
Car(title = "Citroen", imageId = R.drawable.unknown),
Car(title = "Daewoo", imageId = R.drawable.unknown),
Car(title = "Daihatsu", imageId = R.drawable.unknown),
Car(title = "Datsun", imageId = R.drawable.unknown),
Car(title = "Dodge", imageId = R.drawable.unknown),
Car(title = "EXEED", imageId = R.drawable.unknown),
Car(title = "FAW", imageId = R.drawable.unknown),
Car(title = "Ferrari", imageId = R.drawable.unknown),
Car(title = "Fiat", imageId = R.drawable.unknown),
Car(title = "Ford", imageId = R.drawable.unknown),
Car(title = "GAC", imageId = R.drawable.unknown),
Car(title = "GMC", imageId = R.drawable.unknown),
Car(title = "Geely", imageId = R.drawable.unknown),
Car(title = "Genesis", imageId = R.drawable.unknown),
Car(title = "Great Wall", imageId = R.drawable.unknown),
Car(title = "Haval", imageId = R.drawable.unknown),
Car(title = "Honda", imageId = R.drawable.unknown),
Car(title = "Hongqi", imageId = R.drawable.unknown),
Car(title = "Hummer", imageId = R.drawable.unknown),
Car(title = "Hyundai", imageId = R.drawable.unknown),
Car(title = "Infiniti", imageId = R.drawable.unknown),
Car(title = "Isuzu", imageId = R.drawable.unknown),
Car(title = "JAC", imageId = R.drawable.unknown),
Car(title = "Jaguar", imageId = R.drawable.unknown),
Car(title = "Jeep", imageId = R.drawable.unknown),
Car(title = "Jetour", imageId = R.drawable.unknown),
Car(title = "Jetta", imageId = R.drawable.unknown),
Car(title = "Kaiyi", imageId = R.drawable.unknown),
Car(title = "Kia", imageId = R.drawable.unknown),
Car(title = "LADA", imageId = R.drawable.unknown),
Car(title = "Lamborghini", imageId = R.drawable.unknown),
Car(title = "Land Rover", imageId = R.drawable.unknown),
Car(title = "Lexus", imageId = R.drawable.unknown),
Car(title = "Lifan", imageId = R.drawable.unknown),
Car(title = "Lincoln", imageId = R.drawable.unknown),
Car(title = "Livan", imageId = R.drawable.unknown),
Car(title = "Lotus", imageId = R.drawable.unknown),
Car(title = "Mini", imageId = R.drawable.unknown),
Car(title = "Maserati", imageId = R.drawable.unknown),
Car(title = "Maybach", imageId = R.drawable.unknown),
Car(title = "Mazda", imageId = R.drawable.unknown),
Car(title = "McLaren", imageId = R.drawable.unknown),
Car(title = "Mercedes-benz", imageId = R.drawable.mb),
Car(title = "Mitsubishi", imageId = R.drawable.unknown),
Car(title = "Nissan", imageId = R.drawable.unknown),
Car(title = "OMODA", imageId = R.drawable.unknown),
Car(title = "Opel", imageId = R.drawable.unknown),
Car(title = "Peugeot", imageId = R.drawable.unknown),
Car(title = "Plymouth", imageId = R.drawable.unknown),
Car(title = "Polestar", imageId = R.drawable.unknown),
Car(title = "Pontiac", imageId = R.drawable.unknown),
Car(title = "Porsche", imageId = R.drawable.unknown),
Car(title = "RAM", imageId = R.drawable.unknown),
Car(title = "Ravon", imageId = R.drawable.unknown),
Car(title = "Renault", imageId = R.drawable.unknown),
Car(title = "Rolls-Royce", imageId = R.drawable.unknown),
Car(title = "Rover", imageId = R.drawable.unknown),
Car(title = "SEAT", imageId = R.drawable.unknown),
Car(title = "Saab", imageId = R.drawable.unknown),
Car(title = "Scion", imageId = R.drawable.unknown),
Car(title = "Skoda", imageId = R.drawable.unknown),
Car(title = "Skywell", imageId = R.drawable.unknown),
Car(title = "Smart", imageId = R.drawable.unknown),
Car(title = "SsangYong", imageId = R.drawable.unknown),
Car(title = "Subaru", imageId = R.drawable.unknown),
Car(title = "Suzuki", imageId = R.drawable.unknown),
Car(title = "Tank", imageId = R.drawable.unknown),
Car(title = "Tesla", imageId = R.drawable.unknown),
Car(title = "Toyota", imageId = R.drawable.toyota),
Car(title = "Volkswagen", imageId = R.drawable.volkswagen),
Car(title = "Volvo", imageId = R.drawable.volvo),
Car(title = "Vortex", imageId = R.drawable.unknown),
Car(title = "Voyah", imageId = R.drawable.unknown),
Car(title = "ZEEKR", imageId = R.drawable.unknown),
Car(title = "ГАЗ", imageId = R.drawable.unknown),
Car(title = "ЗАЗ", imageId = R.drawable.unknown),
Car(title = "ЗИЛ", imageId = R.drawable.unknown),
Car(title = "ИЖ", imageId = R.drawable.unknown),
Car(title = "Москвич", imageId = R.drawable.unknown),
Car(title = "УАЗ", imageId = R.drawable.unknown)
)