package com.example.thecars.lists

import com.example.thecars.R

//ctrl + j
//ctrl + left mouse
//ctrl + alt + l
//
//123 fhkjsadfb nvvsdf
//ajsdhf 123 afhbkdja
//faslkdj123hjflkasd

const val ACURA_BRAND = "Acura"

val brands: List<String> = listOf(
    ACURA_BRAND,
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Aurus",
    "BMW",
    "Bentley",
    "Buick",
    "Cadillac",
    "Changan",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Daewoo",
    "Daihatsu",
    "Datsun",
    "Dodge",
    "EXEED",
    "FAW",
    "Ferrari",
    "Fiat",
    "Ford",
    "GAC",
    "GMC",
    "Geely",
    "Genesis",
    "Great Wall",
    "Haval",
    "Honda",
    "Hongqi",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "JAC",
    "Jaguar",
    "Jeep",
    "Jetour",
    "Jetta",
    "Kaiyi",
    "Kia",
    "LADA",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lifan",
    "Lincoln",
    "Livan",
    "Lotus",
    "Mini",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "McLaren",
    "Mercedes-benz",
    "Mitsubishi",
    "Nissan",
    "OMODA",
    "Opel",
    "Peugeot",
    "Plymouth",
    "Polestar",
    "Pontiac",
    "Porsche",
    "RAM",
    "Ravon",
    "Renault",
    "Rolls-Royce",
    "Rover",
    "SEAT",
    "Saab",
    "Scion",
    "Skoda",
    "Skywell",
    "Smart",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tank",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "Vortex",
    "Voyah",
    "ZEEKR",
    "ГАЗ",
    "ЗАЗ",
    "ЗИЛ",
    "ИЖ",
    "Москвич",
    "УАЗ",
)

val brandToModels = mapOf(
    ACURA_BRAND to acuraModels,
    "Alfa Romeo" to acuraModels,
    "Aston Martin" to acuraModels,
    "Audi" to acuraModels,
    "Aurus" to acuraModels,
    "BMW" to acuraModels,
    "Bentley" to acuraModels,
    "Buick" to acuraModels,
    "Cadillac" to acuraModels,
    "Changan" to acuraModels,
    "Chery" to acuraModels,
    "Chevrolet" to acuraModels,
    "Chrysler" to acuraModels,
    "Citroen" to acuraModels,
    "Daewoo" to acuraModels,
    "Daihatsu" to acuraModels,
    "Datsun" to acuraModels,
    "Dodge" to acuraModels,
    "EXEED" to acuraModels,
    "FAW" to acuraModels,
    "Ferrari" to acuraModels,
    "Fiat" to acuraModels,
    "Ford" to acuraModels,
    "GAC" to acuraModels,
    "GMC" to acuraModels,
    "Geely" to acuraModels,
    "Genesis" to acuraModels,
    "Great Wall" to acuraModels,
    "Haval" to acuraModels,
    "Honda" to acuraModels,
    "Hongqi" to acuraModels,
    "Hummer" to acuraModels,
    "Hyundai" to acuraModels,
    "Infiniti" to acuraModels,
    "Isuzu" to acuraModels,
    "JAC" to acuraModels,
    "Jaguar" to acuraModels,
    "Jeep" to acuraModels,
    "Jetour" to acuraModels,
    "Jetta" to acuraModels,
    "Kaiyi" to acuraModels,
    "Kia" to acuraModels,
    "LADA" to acuraModels,
    "Lamborghini" to acuraModels,
    "Land Rover" to acuraModels,
    "Lexus" to acuraModels,
    "Lifan" to acuraModels,
    "Lincoln" to acuraModels,
    "Livan" to acuraModels,
    "Lotus" to acuraModels,
    "Mini" to acuraModels,
    "Maserati" to acuraModels,
    "Maybach" to acuraModels,
    "Mazda" to acuraModels,
    "McLaren" to acuraModels,
    "McLaren" to acuraModels,
    "Mercedes-benz" to acuraModels,
    "Mitsubishi" to acuraModels,
    "Nissan" to acuraModels,
    "OMODA" to acuraModels,
    "Opel" to acuraModels,
    "Peugeot" to acuraModels,
    "Plymouth" to acuraModels,
    "Polestar" to acuraModels,
    "Pontiac" to acuraModels,
    "Porsche" to acuraModels,
    "RAM" to acuraModels,
    "Ravon" to acuraModels,
    "Renault" to acuraModels,
    "Rolls-Royce" to acuraModels,
    "Rover" to acuraModels,
    "SEAT" to acuraModels,
    "Saab" to acuraModels,
    "Scion" to acuraModels,
    "Skoda" to acuraModels,
    "Skywell" to acuraModels,
    "Smart" to acuraModels,
    "SsangYong" to acuraModels,
    "Subaru" to acuraModels,
    "Suzuki" to acuraModels,
    "Tank" to acuraModels,
    "Tesla" to acuraModels,
    "Toyota" to acuraModels,
    "Volkswagen" to acuraModels,
    "Volvo" to acuraModels,
    "Vortex" to acuraModels,
    "Voyah" to acuraModels,
    "ZEEKR" to acuraModels,
    "ГАЗ" to acuraModels,
    "ЗАЗ" to acuraModels,
    "ЗИЛ" to acuraModels,
    "ИЖ" to acuraModels,
    "Москвич" to acuraModels,
    "УАЗ" to acuraModels,
)