package com.example.thecars.lists

import com.example.thecars.R

//ctrl + j
//ctrl + left mouse
//ctrl + alt + l
//
//123 fhkjsadfb nvvsdf
//ajsdhf 123 afhbkdja
//faslkdj123hjflkasd

const val ACURA_BRAND = "Acura"

val brands: List<String> = listOf(
    ACURA_BRAND,
    "Alfa Romeo",
    "Aston Martin",
    "Audi",
    "Aurus",
    "BMW",
    "Bentley",
    "Buick",
    "Cadillac",
    "Changan",
    "Chery",
    "Chevrolet",
    "Chrysler",
    "Citroen",
    "Daewoo",
    "Daihatsu",
    "Datsun",
    "Dodge",
    "EXEED",
    "FAW",
    "Ferrari",
    "Fiat",
    "Ford",
    "GAC",
    "GMC",
    "Geely",
    "Genesis",
    "Great Wall",
    "Haval",
    "Honda",
    "Hongqi",
    "Hummer",
    "Hyundai",
    "Infiniti",
    "Isuzu",
    "JAC",
    "Jaguar",
    "Jeep",
    "Jetour",
    "Jetta",
    "Kaiyi",
    "Kia",
    "LADA",
    "Lamborghini",
    "Land Rover",
    "Lexus",
    "Lifan",
    "Lincoln",
    "Livan",
    "Lotus",
    "Mini",
    "Maserati",
    "Maybach",
    "Mazda",
    "McLaren",
    "McLaren",
    "Mercedes-benz",
    "Mitsubishi",
    "Nissan",
    "OMODA",
    "Opel",
    "Peugeot",
    "Plymouth",
    "Polestar",
    "Pontiac",
    "Porsche",
    "RAM",
    "Ravon",
    "Renault",
    "Rolls-Royce",
    "Rover",
    "SEAT",
    "Saab",
    "Scion",
    "Skoda",
    "Skywell",
    "Smart",
    "SsangYong",
    "Subaru",
    "Suzuki",
    "Tank",
    "Tesla",
    "Toyota",
    "Volkswagen",
    "Volvo",
    "Vortex",
    "Voyah",
    "ZEEKR",
    "ГАЗ",
    "ЗАЗ",
    "ЗИЛ",
    "ИЖ",
    "Москвич",
    "УАЗ",
)

val brandToModels = mapOf(
    ACURA_BRAND to R.array.acura_models,
    "Alfa Romeo" to R.array.alfa_romeo,
    "Aston Martin" to R.array.acura_models,
    "Audi" to R.array.acura_models,
    "Aurus" to R.array.acura_models,
    "BMW" to R.array.acura_models,
    "Bentley" to R.array.acura_models,
    "Buick" to R.array.acura_models,
    "Cadillac" to R.array.acura_models,
    "Changan" to R.array.acura_models,
    "Chery" to R.array.acura_models,
    "Chevrolet" to R.array.acura_models,
    "Chrysler" to R.array.acura_models,
    "Citroen" to R.array.acura_models,
    "Daewoo" to R.array.acura_models,
    "Daihatsu" to R.array.acura_models,
    "Datsun" to R.array.acura_models,
    "Dodge" to R.array.acura_models,
    "EXEED" to R.array.acura_models,
    "FAW" to R.array.acura_models,
    "Ferrari" to R.array.acura_models,
    "Fiat" to R.array.acura_models,
    "Ford" to R.array.acura_models,
    "GAC" to R.array.acura_models,
    "GMC" to R.array.acura_models,
    "Geely" to R.array.acura_models,
    "Genesis" to R.array.acura_models,
    "Great Wall" to R.array.acura_models,
    "Haval" to R.array.acura_models,
    "Honda" to R.array.acura_models,
    "Hongqi" to R.array.acura_models,
    "Hummer" to R.array.acura_models,
    "Hyundai" to R.array.acura_models,
    "Infiniti" to R.array.acura_models,
    "Isuzu" to R.array.acura_models,
    "JAC" to R.array.acura_models,
    "Jaguar" to R.array.acura_models,
    "Jeep" to R.array.acura_models,
    "Jetour" to R.array.acura_models,
    "Jetta" to R.array.acura_models,
    "Kaiyi" to R.array.acura_models,
    "Kia" to R.array.acura_models,
    "LADA" to R.array.acura_models,
    "Lamborghini" to R.array.acura_models,
    "Land Rover" to R.array.acura_models,
    "Lexus" to R.array.acura_models,
    "Lifan" to R.array.acura_models,
    "Lincoln" to R.array.acura_models,
    "Livan" to R.array.acura_models,
    "Lotus" to R.array.acura_models,
    "Mini" to R.array.acura_models,
    "Maserati" to R.array.acura_models,
    "Maybach" to R.array.acura_models,
    "Mazda" to R.array.acura_models,
    "McLaren" to R.array.acura_models,
    "McLaren" to R.array.acura_models,
    "Mercedes-benz" to R.array.acura_models,
    "Mitsubishi" to R.array.acura_models,
    "Nissan" to R.array.acura_models,
    "OMODA" to R.array.acura_models,
    "Opel" to R.array.acura_models,
    "Peugeot" to R.array.acura_models,
    "Plymouth" to R.array.acura_models,
    "Polestar" to R.array.acura_models,
    "Pontiac" to R.array.acura_models,
    "Porsche" to R.array.acura_models,
    "RAM" to R.array.acura_models,
    "Ravon" to R.array.acura_models,
    "Renault" to R.array.acura_models,
    "Rolls-Royce" to R.array.acura_models,
    "Rover" to R.array.acura_models,
    "SEAT" to R.array.acura_models,
    "Saab" to R.array.acura_models,
    "Scion" to R.array.acura_models,
    "Skoda" to R.array.acura_models,
    "Skywell" to R.array.acura_models,
    "Smart" to R.array.acura_models,
    "SsangYong" to R.array.acura_models,
    "Subaru" to R.array.acura_models,
    "Suzuki" to R.array.acura_models,
    "Tank" to R.array.acura_models,
    "Tesla" to R.array.acura_models,
    "Toyota" to R.array.acura_models,
    "Volkswagen" to R.array.acura_models,
    "Volvo" to R.array.acura_models,
    "Vortex" to R.array.acura_models,
    "Voyah" to R.array.acura_models,
    "ZEEKR" to R.array.acura_models,
    "ГАЗ" to R.array.acura_models,
    "ЗАЗ" to R.array.acura_models,
    "ЗИЛ" to R.array.acura_models,
    "ИЖ" to R.array.acura_models,
    "Москвич" to R.array.acura_models,
    "УАЗ" to R.array.acura_models,
)